boostcampwm-2022/Web31-CamperRank

- backend/.eslintrc.js
- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- backend/src/typeorm/typeorm-ex.decorator.ts
- backend/src/typeorm/typeorm-ex.module.ts
- backend/src/users/dto/create-user.dto.ts
- backend/src/users/entities/user.entity.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.module.ts
- backend/src/users/users.repository.ts
- backend/src/users/users.service.ts
회원가입 api 개발
2022/11/15
회원가입 API 개발
bcrypt 가 추가되어 `npm install` 필요
> 회원가입 API 개발

- backend/src/app.module.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.service.ts
사용자 검색 API 구현
2022/11/15
사용자 검색 API 구현
> feat: 사용자 검색 API 구현

- frontend/src/components/Footer.tsx
- frontend/src/pages/MainPage.tsx
- frontend/src/styles/Footer.tsx
- frontend/src/styles/GlobalStyle.tsx
- frontend/src/styles/MainHeader.style.tsx
footer 구현 작업 내용 병합
* 2022/11/15
footer 컴포넌트를 만들고, 레이아웃 작성하였습니다.
footer 컴포넌트, footer 스타일 파일
> feat: footer 구현

- backend/src/commons/entities/baseTime.entity.ts
- backend/src/main.ts
- backend/src/test-case/dto/simple-testCase.dto.ts
- backend/src/test-case/entities/test-case.entity.ts
- backend/src/test-case/test-case.controller.ts
- backend/src/test-case/test-case.service.ts
- backend/src/users/dto/simple-user.dto.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.service.ts
API 글로벌 경로 추가
2022/11/17
- global prefix 추가 및 swagger 경로 변경
- service와 controller 구분을 명확하게 수정
- 아직 service와 controller의 구분이 명확하게 되지 않은 부분이 있어서 수정해야한다.
> API 글로벌 경로 추가

- frontend/src/components/MainHeader.tsx
* 2022/11/17
- 헤더의 로그인, 회원가입 버튼 Link 추가
> 헤더 내 버튼에 Link 추가

- frontend/src/components/Home/ProblemList/Problem.tsx
- frontend/src/components/ProblemList/List/List.tsx
- frontend/src/components/ProblemList/List/PageController.tsx
- frontend/src/components/ProblemList/List/Problem.tsx
- frontend/src/components/ProblemList/List/SearchBox.tsx
- frontend/src/components/ProblemList/SearchFilter/Filter.tsx
- frontend/src/components/ProblemList/SearchFilter/Modal.tsx
- frontend/src/components/ProblemList/SearchFilter/Search.tsx
- frontend/src/components/ProblemList/SearchFilter/SearchFilter.tsx
- frontend/src/pages/ProblemList.tsx
* 2022/11/17
- 문제리스트 페이지 레이아웃 크기 재설정
> 문제리스트 페이지 레이아웃 크기 재설정

- gradeServer/.gitignore
- gradeServer/config/express.js
- gradeServer/index.js
- gradeServer/package-lock.json
- gradeServer/package.json
- gradeServer/src/controllers/gradeController.js
- gradeServer/src/routes/gradeRoute.js
* 2022/11/22
- 채점 서버 초기 버전
- 파일 생성 -> 실행 -> 삭제 로직
> feat : 채점서버 초기 버전

- frontend/src/App.tsx
- frontend/src/components/Home/ProblemList/Problem.tsx
- frontend/src/components/ProblemList/List/Problem.tsx
- frontend/src/pages/Problem.tsx
- frontend/src/pages/index.ts
##문제 풀이 페이지 라우팅 구현
* 2022/11/23
- 문제 풀이 페이지 라우팅 구현
> 문제 풀이 페이지 라우팅 구현

- grading/src/controllers/grade.controller.ts
- grading/src/controllers/python.txt
* 2022/11/24
- solution 함수 출력, answer 출력 분리
- 출력 초과, 시간 초과 로직 추가
> fix : 함수 출력, 정답 출력 분리 및 시간 초과 출력 초과 설정

- .github/workflows/ci.yml
- backend/src/app.controller.ts
- backend/src/solved/dto/grade-solved.dto.ts
- backend/src/solved/dto/simple-solved.dto.ts
- backend/src/solved/solved.controller.ts
- backend/src/solved/solved.service.ts
- backend/src/test-case/dto/simple-testCase.dto.ts
- grading/src/controllers/grade.controller.ts
채점 서버 연결 및 동작 테스트
2022/11/24
- 더미 데이터 수정
- 간단한 수준의 파이썬 코드 테스트 구현
> 채점 서버 연결 및 동작 테스트

- backend/src/app.controller.ts
- backend/src/app.module.ts
- backend/src/rank/dto/simple-rank.dto.ts
- backend/src/rank/rank.controller.spec.ts
- backend/src/rank/rank.controller.ts
- backend/src/rank/rank.module.ts
- backend/src/rank/rank.service.spec.ts
- backend/src/rank/rank.service.ts
- backend/src/solved/solved.controller.ts
Feature/rank api
2022/11/28
rank api 추가
> Rank API 생성

- backend/src/solved/solved.controller.ts
- grading/src/controllers/grade.controller.ts
> 자바스크립트 채점 기능 확인

- backend/src/solved/dto/grade-result-solved.dto.ts
- backend/src/solved/solved.controller.ts
- backend/src/solved/solved.service.ts
- grading/src/controllers/grade.controller.ts
feat: grade result 형식 변경
2022/11/29
feat: grade result 형식 변경
> feat: grade result 형식 변경

- backend/src/problem/dto/create-problem.dto.ts
- backend/src/problem/problem.controller.ts
- backend/src/solved/dto/create-solved.dto.ts
- backend/src/solved/dto/update-solved.dto.ts
- backend/src/solved/solved.controller.ts
- backend/src/test-case/test-case.controller.ts
- backend/src/users/dto/create-user.dto.ts
- backend/src/users/users.controller.ts
- backend/src/utils/validation.ts
Feature/cross validator setting
2022/11/30
Feature/cross validator setting
> feat: cross-validator 세팅 및 적용

- frontend/src/components/Problem/Buttons/ProblemButtons.tsx
- frontend/src/components/Problem/Result.tsx
- frontend/src/pages/Problem.tsx
* 2022/11/30
- 문제 풀이 페이지에 채점 기록 남는 오류 제거
- 코드 서버에서 오류일어날 시, 오류 문구 추가
- 문제 창 진입 시 recoil로 저장하던 채점 상태 디폴트로 초기화
> 에디터 결과화면 내 error 제거 및 실행 오류 시 문구 추가

- backend/src/auth/auth.module.ts
- backend/src/auth/auth.service.ts
* 2022/11/30
- 로그인 유효시간 1일로 변경
- 로그인 시 응답값에 1일을 ms로 변환한 값 반환
> feat : 로그인 유효 시간 표시

- backend/src/app.controller.ts
- backend/src/solved/dto/grade-solved.dto.ts
- grading/src/controllers/grade.controller.ts
feat: 테스트 케이스 입력 유형 수정
* YYYY/MM/DD
feat: 테스트 케이스 입력 유형 수정
testInput 의 경우에는 무조건 배열의 형태로 저장된다.
testOutput 의 경우에는 답의 형태에 따라서 저장된다.
> feat: 테스트 케이스 입력 유형 수정

- frontend/package.json
- frontend/src/components/Problem/Video.tsx
- frontend/yarn.lock
- socket/.eslintrc.js
- socket/.prettierrc
- socket/nodemon.json
- socket/package-lock.json
- socket/package.json
- socket/src/app.ts
- socket/tsconfig.json
feat: socket.io server 생성 및 frontend 연결 테스트
2022/11/30
feat: socket.io server 생성 및 frontend 연결 테스트
> feat: socket.io server 생성 및 frontend 연결 테스트

- grading/68983775.py
- grading/src/controllers/grade.controller.ts
* 2022/11/30
- root 계정이 아닌 일반 계정으로 파일 실행 테스트
- 실제 배포 서버에서의 설정이 필요함
> feat: 시스템콜 문제 1차 해결

- frontend/src/components/Problem/Buttons/ProblemButtons.tsx
- frontend/src/components/Problem/Result.tsx
- frontend/src/pages/Problem.tsx
- frontend/src/recoils/gradingState.tsx
* 2022/12/01
- 에디터 크기 변경
- 버튼 입력 방지
- 버튼 disabled 속성 추가하여, 채점 중일 때 true 설정
> feat: 에디터 크기 조정 및 버튼 입력 방지

- frontend/src/components/Problem/Buttons/ProblemButtons.tsx
- frontend/src/components/Problem/Result.tsx
- frontend/src/pages/Problem.tsx
- frontend/src/recoils/gradingState.tsx
* 2022/12/1
- 에디터 오류 및 타입 오류 수정
- gradingstate 타입 변경
- 처음에 에디터 비었을 때만 디폴트 코드 나옴
> fix: 에디터 내 디폴트 코드 및 result 오류 수정

- backend/src/app.controller.ts
> feat: 문제 더미데이터 생성

- backend/src/app.controller.ts
- frontend/src/components/Problem/Buttons/ProblemButtons.tsx
- frontend/src/components/Problem/Content.tsx
- frontend/src/components/Problem/Result.tsx
- frontend/src/pages/Problem.tsx
- frontend/src/types/problem.d.ts
* 2022/12/2
- 문제 풀이 페이지 api연동하여 문제 표시
- dummy api 내 더미 문제 형태 변경
> feat: 문제 풀이페이지 api 연동 완료 및 dummy api 수정

- frontend/src/components/Problem/Content.tsx
- frontend/src/pages/Problem.tsx
* 2022/12/5
에디터 비어있을 때만 디폴트 코드 설정
> fix: 에디터 내 디폴트 코드 초기 설정

- backend/src/users/users.service.ts
fix: mock 수정 및 테스트 정상화
2022/12/06
mock 수정 및 테스트 정상화
> fix: mock 수정 및 테스트 정상화

- frontend/src/components/Home/ProblemList/List.tsx
- frontend/src/components/Problem/Result.tsx
- frontend/src/components/Problem/Video.tsx
- frontend/src/pages/Problem.tsx
- frontend/src/pages/ProblemList.tsx
- frontend/src/recoils/gradingState.tsx
* 2022/12/6
- 타입 오류 로직 변경 및 조건문으로 수정
- webRTC 내 이벤트 핸들러 이벤트 수정
- 객체 구조분해 오류나서 일단 while문으로 채점결과 객체 순회
- 카메라, 마이크 아이콘 추가 및 socket, webrtc 이용하여 동작 구현
> fix: 타입 오류 및 webRTC 오류 수정

- backend/src/main.ts
- grading/src/app.ts
Feature/https setting
2022/12/06
nestjs, express https 세팅
> feat: https 설정

- frontend/src/components/Home/ProblemList/List.tsx
- frontend/src/components/Problem/Buttons/ProblemButtons.tsx
- frontend/src/components/Problem/Result.tsx
- frontend/src/pages/Problem.tsx
- frontend/src/pages/ProblemList.tsx
- socket/src/app.ts
* 2022/12/7
- api response 부분 statusCode 200일 때만 동작하는 부분 삭제
> fix: api response 부분 수정

- .github/workflows/deployment.yml
- backend/src/solved/solved.controller.ts
- backend/src/solved/solved.service.ts
- grading/src/controllers/grade.controller.ts
feat: NCP의 Cloud Functions를 이용한 채점 기능 구현
2022/12/07
- NCP의 Cloud Functions를 이용한 채점 기능 구현
- cd install 옵션 추가 및 ssh-action 수정
> feat: NCP의 Cloud Functions를 이용한 채점 기능 구현

- frontend/.eslintrc.cjs
- frontend/package.json
- frontend/src/components/Home/ProblemList/Problem.tsx
- frontend/src/components/Problem/Buttons/ProblemButtons.tsx
- frontend/src/components/Problem/Content.tsx
- frontend/src/components/Problem/LanguageSelector.tsx
- frontend/src/pages/Problem.tsx
- frontend/src/pages/ProblemList.tsx
- frontend/src/utils/theme.ts
- frontend/yarn.lock
* 2022/12/8
- 에디터 내 언어 변경
- 에디터 디폴트 코드 파라미터 문제에 맞춰서 수정
- setTimeout 적용하여, 같이 풀기 시 에디터 상태 비어있을 때만 디폴트 코드 추가
- 에디터 언어 인식 javascript + python
- 에디터에 언어 둘다 인식하게 하였는데, syntax highlighting이 사라져서 추후 알아봐야할듯
- settimeout말고 더 좋은 방법이 있을것같다
> feat: 에디터 내 언어 변경

- backend/src/solved/solved.controller.ts
- grading/src/controllers/grade.controller.ts
feat: Cloud Functions에 python 채점 코드 추가 및 API 서버에 연결
2022/12/11
Cloud Functions에 python 채점 코드 추가 및 API 서버에 연결
> feat: Cloud Functions에 python 채점 코드 추가 및 API 서버에 연결

- frontend/src/App.tsx
- frontend/src/components/Home/Banner/Banner.tsx
- frontend/src/components/Home/Banner/BannerContent.tsx
- frontend/src/components/Home/Banner/BannerController.tsx
- frontend/src/components/Home/Banner/BannerImage.tsx
- frontend/src/components/Home/Banner/BannerText.tsx
- frontend/src/components/Home/ProblemList/List.tsx
- frontend/src/components/Home/ProblemList/Problem.tsx
- frontend/src/components/MainHeader.tsx
- frontend/src/components/ProblemList/List/List.tsx
- frontend/src/components/ProblemList/List/PageController.tsx
- frontend/src/components/ProblemList/List/Problem.tsx
- frontend/src/components/ProblemList/List/SearchBox.tsx
- frontend/src/components/ProblemList/SearchFilter/Filter.tsx
- frontend/src/components/ProblemList/SearchFilter/Modal.tsx
- frontend/src/components/ProblemList/SearchFilter/SearchFilter.tsx
- frontend/src/components/SignIn/InputForm.tsx
- frontend/src/components/SignUp/InputForm.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/ProblemList.tsx
- frontend/src/pages/Sign.tsx
- frontend/src/pages/SignIn.tsx
- frontend/src/pages/index.ts
- frontend/src/styles/MainHeader.style.tsx
- frontend/src/styles/SignIn.style.tsx
- frontend/src/styles/SignUp.style.tsx
*2022/12/11
- 메인, 문제리스트, 로그인, 회원가입 페이지 레이아웃 수정
- 회원가입 시 아이디 체크 로직 변경
-  필터 모달 외부 클릭되어도 닫히지 않는 오류 변경
> feat: 메인, 문제 리스트 페이지, 로그인, 회원가입 페이지 레이아웃 수정

- frontend/src/components/Home/ProblemList/List.tsx
* 2022/12/12
- 비로그인 시 fetchURL 변경
- lgoinId X => loginId 0으로 바꿔서 보냄
> fix: 비로그인 시 랜덤 문제 오류 수정

- backend/src/rank/dto/simple-rank.dto.ts
- backend/src/rank/rank.controller.ts
- backend/src/rank/rank.service.ts
- backend/src/users/users.controller.ts
feat: rank api에서 loginId를 반환하도록 수정
2022/12/12
rank api에서 loginId를 반환하도록 수정
> feat: rank api에서 loginId를 반환하도록 수정

- frontend/src/components/Home/Banner/Banner.tsx
- frontend/src/components/Home/Banner/BannerController.tsx
- frontend/src/components/Problem/LanguageSelector.tsx
- frontend/src/components/Problem/Video.tsx
- frontend/src/components/ProblemList/List/List.tsx
- frontend/src/components/ProblemList/List/PageController.tsx
- frontend/src/components/ProblemList/List/Problem.tsx
- frontend/src/pages/Problem.tsx
- socket/src/app.ts
> fix :기존 소켓 코드 삭제

- frontend/src/recoils/index.ts
- frontend/src/recoils/socketState.tsx
* 2022/12/14
socket recoil state 삭제
> fix: socket recoil state 삭제

- frontend/src/pages/Problem.tsx
> fix: param 개수 오류 수정

- frontend/package.json
- frontend/vite.config.ts
- frontend/yarn.lock
nginx 압축에서 build 시 압축으로 변경
* 2022/12/15
빌드 시 gzip 압축 설정
nginx 압축 모드에서 gz파일 찾도록 설정 필요
> feat: nginx 압축에서 build 시 압축으로 변경

- frontend/src/components/Home/Banner/Banner.tsx
- frontend/src/components/Home/Banner/BannerController.tsx
- frontend/src/components/Home/ProblemList/Problem.tsx
- frontend/src/components/ProblemList/List/List.tsx
- frontend/src/components/ProblemList/List/Problem.tsx
- frontend/src/components/ProblemList/List/SearchBox.tsx
- frontend/src/components/ProblemList/SearchFilter/Filter.tsx
- frontend/src/components/ProblemList/SearchFilter/Search.tsx
- frontend/src/components/ProblemList/SearchFilter/SearchFilter.tsx
- frontend/src/pages/ProblemList.tsx
- frontend/src/recoils/filterState.ts
* 2022/12/15
- 체크 박스 추가 및 배너 초기 렌더링 수정
- 스로틀링 시간 간격 축소 및 배너 내 컨트롤러 렌더링 수정
- 문제 푼 상태 표시하는 체크박스 추가
- 컴포넌트 memo 적용
> feat: 문제 풀이 페이지 내 문제 푼 상태 체크박스 추가

- frontend/src/utils/defaultCode.ts
> fix: default python code 수정

- frontend/src/pages/ProblemList.tsx
> fix: fetch URL 재설정
